### ISSUE TITLE
[2.0.0-alpha.4]Cannot find module 'babel-polyfill/regenerator-runtime/runtime'

### ISSUE THREAD

**Issue by JounQin** [babel/babel-preset-env#262]
babel-polyfill: 7.0.0-alpha.7

babel-preset-env 2.0.0-alpha.3 works well.

**Comment by phyllisstein** [comment]
Just ran into this myself, with identical module versions, and can confirm that rolling back to `babel-preset-env@2.0.0-alpha.3` resolved the issue. Happy to provide any color if it's useful!

**Comment by JounQin** [comment]
Yes, I've rolled back to *2.0.0-alpha.3*, but this should be fixed.

**Comment by hzoo** [comment]
Didn't do much oss over the weekend, can look at it today. Thanks for trying of the alpha version! (But then again just a reminder it's alpha still 😄 )

**Comment by hzoo** [comment]
Ok it's because I assumed that I didn't need to add `/lib` or we need to move those files 1 level up.

https://github.com/babel/babel-preset-env/pull/263 for a PR

**Comment by hzoo** [comment]
https://github.com/babel/babel-preset-env/issues/263, should be fixed in v2.0.0-alpha.5

**Comment by JounQin** [comment]
@hzoo Hmm... After upgrading to v2.0.0-alpha.5 it occurs another error as following:
``` log
import 'babel-polyfill/lib/core-js/modules/es6.symbol';
^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.require.extensions.(anonymous function) [as .js] (/local/GitHub/vue-music/node_modules/babel-register/lib/node.js:114:50)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/local/GitHub/vue-music/server/index.js:7:1)
error Command failed with exit code 1.
```

I'm using `babel-loader` with `webpack`.
